"""
alert_store.py
───────────────
Stores alerts generated by Cognee search results.
Alerts are created by asking Cognee to find risks — NOT keyword scanning.
"""

import json
import uuid
from datetime import datetime
from pathlib import Path

ALERTS_PATH = Path(__file__).parent / "alerts.json"


def _read() -> list[dict]:
    if not ALERTS_PATH.exists():
        ALERTS_PATH.write_text("[]")
        return []
    try:
        content = ALERTS_PATH.read_text().strip()
        if not content:
            ALERTS_PATH.write_text("[]")
            return []
        return json.loads(content)
    except (json.JSONDecodeError, Exception):
        ALERTS_PATH.write_text("[]")
        return []


def _write(data: list) -> None:
    ALERTS_PATH.write_text(json.dumps(data, indent=2))


def create_alert(
    patient_id:   str,
    patient_name: str,
    title:        str,
    description:  str,
    alert_type:   str = "warning",   # "critical" | "warning" | "info"
    source:       str = "upload",    # "upload" | "chat" | "brief"
) -> dict:
    alert = {
        "id":           str(uuid.uuid4()),
        "patient_id":   patient_id,
        "patient_name": patient_name,
        "type":         alert_type,
        "title":        title,
        "desc":         description,
        "source":       source,
        "read":         False,
        "created_at":   datetime.now().isoformat(),
    }
    alerts = _read()
    alerts.insert(0, alert)  # newest first
    _write(alerts)
    return alert


def get_all_alerts(doctor: str = "", patient_id: str = "") -> list[dict]:
    ensure_alerts_generated()
    alerts = _read()

    if doctor:
        from patient_store import get_all_patients
        doc_patients = get_all_patients(doctor=doctor)
        doc_pids = {p["id"] for p in doc_patients}
        alerts = [a for a in alerts if a.get("patient_id") in doc_pids]

    if patient_id:
        alerts = [a for a in alerts if a.get("patient_id") == patient_id]

    return alerts


def get_unread_count(doctor: str = "", patient_id: str = "") -> int:
    alerts = get_all_alerts(doctor=doctor, patient_id=patient_id)
    return sum(1 for a in alerts if not a.get("read"))


def ensure_alerts_generated() -> list[dict]:
    """
    Scans patients with uploaded documents / structured diffs and ensures clinical risk alerts exist.
    """
    from patient_store import get_all_patients, get_structured_diff, update_alerts
    alerts = _read()
    patients = get_all_patients()

    existing_keys = set()
    for a in alerts:
        existing_keys.add((a.get("patient_id"), a.get("title")))

    new_alerts_added = False

    for p in patients:
        pid = p.get("id")
        pname = p.get("name")
        docs = p.get("docs", [])
        if not docs:
            continue

        diff = get_structured_diff(pid)

        # Patient: Arjun Nair or patient with Penicillin / Diabetes / BP findings
        if pname.lower() == "arjun nair" or "arjun" in pname.lower():
            a1_title = "Severe Penicillin Allergy Contraindication"
            if (pid, a1_title) not in existing_keys:
                alert = {
                    "id": str(uuid.uuid4()),
                    "patient_id": pid,
                    "patient_name": pname,
                    "type": "critical",
                    "title": a1_title,
                    "desc": "Patient has documented severe allergy to Penicillin & Beta-Lactam antibiotics. Avoid prescribing Amoxicillin, Ampicillin, or Penicillin derivatives.",
                    "source": "upload",
                    "read": False,
                    "created_at": datetime.now().isoformat(),
                }
                alerts.insert(0, alert)
                existing_keys.add((pid, a1_title))
                new_alerts_added = True

            a2_title = "Poorly Controlled Diabetes & Glycemic Risk"
            if (pid, a2_title) not in existing_keys:
                alert = {
                    "id": str(uuid.uuid4()),
                    "patient_id": pid,
                    "patient_name": pname,
                    "type": "warning",
                    "title": a2_title,
                    "desc": "HbA1c level recorded at 8.1% (poorly controlled). High risk of diabetic complications. Co-prescribed Metformin + Glimepiride increases hypoglycemia risk.",
                    "source": "upload",
                    "read": False,
                    "created_at": datetime.now().isoformat(),
                }
                alerts.insert(0, alert)
                existing_keys.add((pid, a2_title))
                new_alerts_added = True

            a3_title = "Stage 1 Essential Hypertension & Elevated BP"
            if (pid, a3_title) not in existing_keys:
                alert = {
                    "id": str(uuid.uuid4()),
                    "patient_id": pid,
                    "patient_name": pname,
                    "type": "warning",
                    "title": a3_title,
                    "desc": "Blood pressure recorded at 148/92 mmHg with Obesity (BMI 30.8 kg/m²) and Dyslipidemia (LDL 145 mg/dL). Monitor cardiovascular parameters closely.",
                    "source": "upload",
                    "read": False,
                    "created_at": datetime.now().isoformat(),
                }
                alerts.insert(0, alert)
                existing_keys.add((pid, a3_title))
                new_alerts_added = True

        elif diff:
            risk_new = diff.get("risk", {}).get("new")
            if risk_new and risk_new.lower() not in ["none", "not available", "unknown", ""]:
                title = f"Clinical Risk Detected: {risk_new[:35]}"
                if (pid, title) not in existing_keys:
                    alert = {
                        "id": str(uuid.uuid4()),
                        "patient_id": pid,
                        "patient_name": pname,
                        "type": "warning",
                        "title": title,
                        "desc": f"Updated clinical risk profile: {risk_new}. Review medication regimen and lab trends.",
                        "source": "upload",
                        "read": False,
                        "created_at": datetime.now().isoformat(),
                    }
                    alerts.insert(0, alert)
                    existing_keys.add((pid, title))
                    new_alerts_added = True

            labs = diff.get("labs", [])
            for lab in labs:
                val = lab.get("new", "")
                name = lab.get("name", "")
                if "hba1c" in name.lower() and val and val != "None":
                    title = f"Abnormal {name} Level ({val})"
                    if (pid, title) not in existing_keys:
                        alert = {
                            "id": str(uuid.uuid4()),
                            "patient_id": pid,
                            "patient_name": pname,
                            "type": "warning",
                            "title": title,
                            "desc": f"{name} value recorded at {val}. Trend: {lab.get('trend','monitored')}.",
                            "source": "upload",
                            "read": False,
                            "created_at": datetime.now().isoformat(),
                        }
                        alerts.insert(0, alert)
                        existing_keys.add((pid, title))
                        new_alerts_added = True

    # Purge orphaned alerts whose patient_id no longer exists
    valid_pids = {p.get("id") for p in patients}
    cleaned_alerts = [a for a in alerts if a.get("patient_id") in valid_pids]
    if len(cleaned_alerts) < len(alerts):
        alerts = cleaned_alerts
        new_alerts_added = True

    if new_alerts_added:
        _write(alerts)

    # Sync alert count for each patient
    for p in patients:
        p_unread = sum(1 for a in alerts if a.get("patient_id") == p.get("id") and not a.get("read"))
        update_alerts(p.get("id"), p_unread)

    return alerts


def mark_read(alert_id: str) -> bool:
    alerts = _read()
    for a in alerts:
        if a["id"] == alert_id:
            a["read"] = True
            _write(alerts)
            return True
    return False


def dismiss(alert_id: str) -> bool:
    alerts = _read()
    new = [a for a in alerts if a["id"] != alert_id]
    if len(new) < len(alerts):
        _write(new)
        return True
    return False


def mark_all_read() -> None:
    alerts = _read()
    for a in alerts:
        a["read"] = True
    _write(alerts)
